# Generated by Django 5.2 on 2025-04-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluk', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('literacy_rate', models.FloatField()),
                ('health_centers', models.IntegerField()),
                ('schools', models.IntegerField()),
                ('famous_for', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='statecolor',
            name='state_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
