# Generated by Django 5.2 on 2025-05-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_regioninfo_alter_statecolor_state_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regioninfo',
            old_name='famous_for',
            new_name='taluk_famous_for',
        ),
    ]
