# Generated by Django 5.2 on 2025-05-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0003_rename_famous_for_regioninfo_taluk_famous_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regioninfo',
            old_name='taluk_famous_for',
            new_name='famous_for',
        ),
    ]
